# Use Python base image
FROM python:3.13-alpine

# Set working directory
WORKDIR /app

ENV PATH="/root/.cargo/bin:${PATH}"

# Copy Python dependencies first
COPY requirements.txt ./

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of your application code
COPY . .

# Expose FastAPI port
EXPOSE 5200

# Command to run app
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5200", "--workers", "8"]