name: Endpoint Integration Test

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main
    workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
    test-service:
        runs-on: ubuntu-latest
        env:
            SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
            SUPABASE_API_KEY: ${{ secrets.SUPABASE_API_KEY }}
            
        defaults:
            run:
                working-directory: ./backend
        
        steps:
            - name: 📥 Checkout code
              uses: actions/checkout@v4
            
            - name: Setup Go
              uses: actions/setup-go@v4
              with:
                go-version: '1.25'
            
            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Start services
              run: docker compose up -d --build
            
            - name: Wait for services to be ready
              run: |
                echo "Waiting for services to start..."
                sleep 5s # Adjust this sleep time as needed based on your service startup time.
                echo "Services should be up now."
            
            - name: Run go test integration tests
              run: cd ../test/integration; go test -v 

            - name: Container Cleanup
              if: always()
              run: docker-compose down