name: Consolidated Microservices Unit Testing

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main
    workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
    unit_testing:
        runs-on: ubuntu-latest
    
        steps:
            - name: 📥 Checkout code
              uses: actions/checkout@v4
            
            - name: Install Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.13"
            
            - name: Install Python Dependencies
              run: |
                    python -m pip install --upgrade pip
                    pip install pytest pytest-cov coveralls supabase dotenv fastapi httpx pydantic uvicorn
                    pip install \
                    fastapi \
                    starlette \
                    pydantic \
                    httpx \
                    anyio \
                    uvicorn \
                    pytest \
                    pytest-cov \
                    pytest-asyncio
            
            - name: Running Unit Tests & Generating Coverage Report
              run: |
                  pytest -v --cov=./backend/services/ test/unit/
            
            - name: Upload coverage to Coveralls
              uses: coverallsapp/github-action@v2
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
              env:
                  COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

